<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: books.proto

namespace Books;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Message for handling a Book list response
 * </pre>
 *
 * Protobuf type <code>Books.BookListResponse</code>
 */
class BookListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .Books.Book books = 1;</code>
     */
    private $books;

    public function __construct() {
        \GPBMetadata\Books::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .Books.Book books = 1;</code>
     */
    public function getBooks()
    {
        return $this->books;
    }

    /**
     * <code>repeated .Books.Book books = 1;</code>
     */
    public function setBooks(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Books\Book::class);
        $this->books = $arr;
    }

}

