<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: books.proto

namespace Books;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Message Type for handling a single Book
 * </pre>
 *
 * Protobuf type <code>Books.Book</code>
 */
class Book extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * <code>repeated .Books.Genre genres = 3;</code>
     */
    private $genres;
    /**
     * <code>.Books.Author author = 4;</code>
     */
    private $author = null;
    /**
     * <code>.Books.Book.Published published = 5;</code>
     */
    private $published = 0;

    public function __construct() {
        \GPBMetadata\Books::initOnce();
        parent::__construct();
    }

    /**
     * <code>string id = 1;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <code>string id = 1;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;
    }

    /**
     * <code>string name = 2;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <code>string name = 2;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <code>repeated .Books.Genre genres = 3;</code>
     */
    public function getGenres()
    {
        return $this->genres;
    }

    /**
     * <code>repeated .Books.Genre genres = 3;</code>
     */
    public function setGenres(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Books\Genre::class);
        $this->genres = $arr;
    }

    /**
     * <code>.Books.Author author = 4;</code>
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * <code>.Books.Author author = 4;</code>
     */
    public function setAuthor(&$var)
    {
        GPBUtil::checkMessage($var, \Books\Author::class);
        $this->author = $var;
    }

    /**
     * <code>.Books.Book.Published published = 5;</code>
     */
    public function getPublished()
    {
        return $this->published;
    }

    /**
     * <code>.Books.Book.Published published = 5;</code>
     */
    public function setPublished($var)
    {
        GPBUtil::checkEnum($var, \Books\Book_Published::class);
        $this->published = $var;
    }

}

