<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: books.proto

namespace Books;

/**
 * Protobuf enum <code>Books.Book.Published</code>
 */
class Book_Published
{
    /**
     * <code>UNPUBLISHED = 0;</code>
     */
    const UNPUBLISHED = 0;
    /**
     * <code>PUBLISHED = 1;</code>
     */
    const PUBLISHED = 1;
}

