<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: books.proto

namespace Books;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Message for handling an empty request
 * </pre>
 *
 * Protobuf type <code>Books.EmptyMessage</code>
 */
class EmptyMessage extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Books::initOnce();
        parent::__construct();
    }

}

